version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "MyFacStack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wcaw16jkrzww"
s3_prefix = "MyFacStack"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

